// These Codes are generated by kakaTools ProtocolGenerater v1.3
// ------------------------------------------------------------------
//
// Copyright (c) 2015 linchen.
// All rights reserved.
//
// Email: superkaka.org@gmail.com
//
// ------------------------------------------------------------------

package protocol
{
    public class Protocol
    {
        
        //登录
        static public const sendLogin:int = 3;
        
        //技能打击伤害
        static public const testCommonStruct:int = 006;
        
        //
        static public const sendString:int = 100;
        
    }
}
