// These Codes are generated by kakaTools ExcelExport v2.0
// ------------------------------------------------------------------
//
// Copyright (c) 2015 linchen.
// All rights reserved.
//
// Email: superkaka.org@gmail.com
//
// ------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;
using KLib.utils;

public class LangVO
{
    
    //
    private string _Id;
    public string Id
    {
        get { return _Id; }
    }
    
    //名字
    private string _Text;
    public string Text
    {
        get { return _Text; }
    }
    
    //年龄
    private int _Age;
    public int Age
    {
        get { return _Age; }
    }
    
    //性别
    private bool _Sex;
    public bool Sex
    {
        get { return _Sex; }
    }
    
    //
    private float _Jump;
    public float Jump
    {
        get { return _Jump; }
    }
    
    //
    private DateTime _Time;
    public DateTime Time
    {
        get { return _Time; }
    }
    

    public void decode(EndianBinaryReader binReader)
    {
    
            _Id = binReader.ReadUTF();
            
            _Text = binReader.ReadUTF();
            
            _Age = int.Parse(binReader.ReadUTF());
            
            var str_Sex = binReader.ReadUTF();
            _Sex = (str_Sex.ToLower() == "true" || str_Sex == "1");
            
            _Jump = float.Parse(binReader.ReadUTF());
            
            _Time = DateTime.Parse(binReader.ReadUTF());
            
    }

    static public void Fill(byte[] bytes)
    {

        var binReader = new EndianBinaryReader(Endian.LittleEndian, new MemoryStream(bytes));
        binReader.Endian = binReader.ReadBoolean() ? Endian.LittleEndian : Endian.BigEndian;
        
        
        var jumpPos = binReader.ReadInt32();
        
        //跳过表头信息
        binReader.BaseStream.Position = jumpPos;
        
        /*
        var headerCount = binReader.ReadInt32();
        var headers = new string[headerCount];
        var types = new string[headerCount];
        for (var i = 0; i < headerCount; i++)
        {
            headers[i] = binReader.ReadUTF();
            types[i] = binReader.ReadUTF();
        }
        */
        
        var count = binReader.ReadInt32();
        for (int i = 0; i < count; i++)
        {
            var vo = new LangVO();
            vo.decode(binReader);
            list_vo.Add(vo);
            dic_vo.Add(vo.Age, vo);
        }

    }

    static private Dictionary<int, LangVO> dic_vo = new Dictionary<int, LangVO>();
    static private List<LangVO> list_vo = new List<LangVO>();

    static public IList<LangVO> GetVOList()
    {
        return list_vo.AsReadOnly();
    }

    static public LangVO GetVO(int Age)
    {
        return dic_vo[Age];
    }

    static public IList<LangVO> Where(Func<LangVO, bool> filter)
    {
        return list_vo.Where(filter).ToList();
    }

}
