// These Codes are generated by kakaTools ProtocolGenerater v1.3
// ------------------------------------------------------------------
//
// Copyright (c) 2015 linchen.
// All rights reserved.
//
// Email: superkaka.org@gmail.com
//
// ------------------------------------------------------------------

package protocol.vo
{
	import flash.utils.ByteArray;
  import protocol.*;
	import org.superkaka.KLib.net.protocol.*;

    //玩家列表
    public class sendLogin_playerListVO
    {
        
        //战场唯一id
        public var battleId:int;
        //
        public var teamId:int;
        //
        public var actorId:int;
        //当前x
        public var curX:int;
        //当前y
        public var curY:int;
        //走路0，跑1
        public var fast:Boolean;
        
        
        public function decode(binReader:ProtocolByteArray):void
        {
		
            battleId = binReader.readShort();
            
            teamId = binReader.readShort();
            
            actorId = binReader.readShort();
            
            curX = binReader.readShort();
            
            curY = binReader.readShort();
            
            fast = binReader.readBoolean();
            
        }
        
        public function encode(binWriter:ProtocolByteArray):void
        {
		
            binWriter.writeShort(battleId);
            
            binWriter.writeShort(teamId);
            
            binWriter.writeShort(actorId);
            
            binWriter.writeShort(curX);
            
            binWriter.writeShort(curY);
            
            binWriter.writeBoolean(fast);
            
        }
        
    }

}
