// These Codes are generated by kakaTools ProtocolGenerater v1.3
// ------------------------------------------------------------------
//
// Copyright (c) 2015 linchen.
// All rights reserved.
//
// Email: superkaka.org@gmail.com
//
// ------------------------------------------------------------------

package protocol.vo
{
	import flash.utils.ByteArray;
	import protocol.*;
	import org.superkaka.KLib.net.protocol.*;

    //
    public class sendStringVO extends BaseVO
    {
        
        //
        public var str:String;
        
        
        public function sendStringVO():void
        {
			super(Protocol.sendString);
        }
        
        override public function decode(binReader:ProtocolByteArray):void
        {
		
            str = binReader.readUTF();
            
        }
        
        override public function encode(binWriter:ProtocolByteArray):void
        {
		
            binWriter.writeUTF(str);
            
        }
        
    }

}

