// These Codes are generated by kakaTools ProtocolGenerater v1.3
// ------------------------------------------------------------------
//
// Copyright (c) 2015 linchen.
// All rights reserved.
//
// Email: superkaka.org@gmail.com
//
// ------------------------------------------------------------------

package protocol.vo
{
	import flash.utils.ByteArray;
	import protocol.*;
	import org.superkaka.KLib.net.protocol.*;

    //技能打击伤害
    public class testCommonStructVO extends BaseVO
    {
        
        //战场唯一id
        public var battleId:int;
        //链接公用结构体
        public var damageList:Vector.<CommonStructVO>;
        
        
        public function testCommonStructVO():void
        {
			super(Protocol.testCommonStruct);
        }
        
        override public function decode(binReader:ProtocolByteArray):void
        {
		
            battleId = binReader.readShort();
            
            var len_damageList:int = binReader.readUnsignedShort();
            damageList = new Vector.<CommonStructVO>();
            for (var i:int = 0; i < len_damageList; i++)
            {

            damageList[i] = new CommonStructVO();
            damageList[i].decode(binReader);
            
            }
            
        }
        
        override public function encode(binWriter:ProtocolByteArray):void
        {
		
            binWriter.writeShort(battleId);
            
			var len_damageList:int = damageList.length;
			binWriter.writeShort(len_damageList);
            for (var i:int = 0; i < len_damageList; i++)
            {

            damageList[i].encode(binWriter);
            
            }
            
        }
        
    }

}

