// These Codes are generated by kakaTools ProtocolGenerater v1.3
// ------------------------------------------------------------------
//
// Copyright (c) 2015 linchen.
// All rights reserved.
//
// Email: superkaka.org@gmail.com
//
// ------------------------------------------------------------------

using System;

namespace protocol
{
    public class Protocol
    {
        
        //登录
        public const int sendLogin = 3;
        
        //技能打击伤害
        public const int testCommonStruct = 006;
        
        //
        public const int sendString = 100;
        
    }
}
